version: '3.9'

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - '27017:27017'
    networks:
      - network-backend

  top.api:
    depends_on:
      - mongo
    image: top-api:latest
    container_name: top-api
    restart: always
    ports:
      - '3000:3000'
    volumes:
      - ./.env:/opt/app/.env
    links:
      - mongo
    networks:
      - network-backend

networks:
  network-backend:
